# Generated by Django 4.2.5 on 2024-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="delete_status",
        ),
    ]
