# Generated by Django 4.2.5 on 2024-04-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0002_alter_category_image_products"),
        ("user", "0003_alter_customer_name_alter_customer_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[
                            (1, "order_confirmed"),
                            (2, "order_processed"),
                            (3, "order_delivered"),
                            (3, "order_rejected"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "delete_status",
                    models.IntegerField(
                        choices=[(1, "live"), (0, "delete")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="user.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderdItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_items",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_carts",
                        to="product.products",
                    ),
                ),
            ],
        ),
    ]
